#!/bin/bash

# SOMATYPUS: A PLATYPUS-BASED VARIANT CALLING PIPELINE FOR CANCER DATA
# Adrian Baez-Ortega, Transmissible Cancer Group, University of Cambridge
# 2016

# somatypus
# Core pipeline script

# INPUT
# -i: path to folder containing the input BAM files (accompanied by BAI indices)
# -g: path to genome FASTA (must have FAI index)
# -o: path to global output folder
# -r: path to file of regions in chr:start-end format (optional)
# -c: number of CPUs (processes) for Platypus (*SHOULD NOT EXCEED 8 DUE TO BUG*) (optional)
# -e: extra options for Platypus (within quotes, separated by spaces) (optional)



VERSION=1.3


####################################### FUNCTIONS #######################################

# AUXILIARY FUNCTIONS
# print_help()
# Prints a help guide if -h, or no arguments, are input
print_help() {
    echo
    echo
    echo "| SOMATYPUS"
    echo "| A Platypus-based variant calling pipeline for cancer data"
    echo "| somatyups-farm-1 $VERSION"
    echo "|"    
    echo "| Required input:"
    echo "|    -i  Absolute path to folder containing the input BAM files (accompanied by BAI indices)."
    echo "|    -g  Absolute path to reference genome FASTA file (accompanied by FAI index)."
    echo "|    -o  Absolute path to the output folder (it will be created if needed)."
    echo "|"
    echo "| Optional input:"
    echo "|    -r  Absolute path to file of regions to use, one per line in CHR:START-END format."
    echo "|    -c  Number of CPUs (processes) for Platypus *(should not exceed 8 due to a bug)*."
    echo "|    -p  Additional options for Platypus, within quotes and separated by spaces."
    echo "|"
    echo "| Options:"
    echo "|    -h  Print this usage information and exit."
    echo "|    -v  Print version and exit."
    echo "|"
    echo "| Usage:"
    echo "|    somatyups-farm-1 -i /path/to/bams_dir -o /path/to/out_dir -g /path/to/genome.fna -r /path/to/regions.txt -c <1-8> -p \"--option=VAL --option=VAL\""
    echo
    echo
}


# check_file()
# Checks if a file exists and is not empty. In that case, it displays an error message and exits
# Used for checking the output of each step
check_file() {

    if [ ! -s $1 ]; then
        echo -e "\nERROR: Output file $1 was not correctly generated. Please check the logs folder for more information.\n" >&2
        exit 1
    fi
    
}


# 6) merge_calls()
# Merges filtered Platypus SNV calls obtained from individual calling
merge_calls() {
    mkdir -p $OUTDIR/5-7_merged
    # Create a list of filtered individual VCFs
    ls -1 $OUTDIR/4_individual_filtered/*.filtered.vcf > $OUTDIR/4_individual_filtered/list.txt

    # Merge SNVs from all filtered VCFs
    bsub -o $OUTDIR/logs/1_individual_default/log.%J \
              -e $OUTDIR/logs/1_individual_default/err.%J \
              -q normal \
              -n $CPUS \
              -R 'span[hosts=1] select[mem>=10000] rusage[mem=10000]' -M10000 \
    "Somatypus_SNVmerge.py $OUTDIR/4_individual_filtered/list.txt $OUTDIR/5-7_merged > $OUTDIR/logs/6_SNV_merge.log"
}

################################### END OF FUNCTIONS ####################################


# Check that dependencies (Platypus, tabix, bgzip, vcf-sort, Somatypus scripts) are installed
hash Platypus.py 2>/dev/null || { echo -e "\nERROR: Platypus.py: command not found. Please install Platypus and add its directory to your PATH.\n" >&2; exit 1; }    
hash tabix 2>/dev/null || { echo -e "\nERROR: tabix: command not found. Please install the SAMtools tabix package and add its directory to your PATH.\n" >&2; exit 1; } 
   
hash bgzip 2>/dev/null || { echo -e "\nERROR: bgzip: command not found. Please install the SAMtools tabix package and add its directory to your PATH.\n" >&2; exit 1; } 
   
hash vcf-sort 2>/dev/null || { echo -e "\nERROR: vcf-sort: command not found. Please install VCFtools and add its directory to your PATH.\n" >&2; exit 1; }    
hash Somatypus_SplitMA-MNVs.py 2>/dev/null || { echo -e "\nERROR: Somatypus directory not included in the PATH. Please add the somatypus/src directory to your PATH.\n" 
>&2; exit 1; }    



# If no arguments (or -h): print help
if [ "$#" -eq 0 ]; then
    print_help
    exit 0
fi


# Parse input
BAMSDIR=""
REFERENCE=""
REGIONS="no"
OUTDIR=""
CPUS=1
EXTRA=""
while getopts ":i:g:r:o:c:p:hv?" OPT; do
  case $OPT in
    i)
      BAMSDIR=$OPTARG
      ;;
    g)
      REFERENCE=$OPTARG
      ;;
    r)
      REGIONS=$OPTARG
      ;;
    o)
      OUTDIR=$OPTARG
      ;;
    c)
      CPUS=$OPTARG
      ;;
    p)
      EXTRA=$OPTARG
      ;;
    h)
      print_help
      exit 0
      ;;
    v)
      echo "Somatypus $VERSION"
      exit 0
      ;;
    \?)
      print_help
      echo -e "Invalid option: -$OPTARG\n" >&2
      exit 1
      ;;
  esac
done


# Check that all mandatory inputs are present
if [ -z "$BAMSDIR" ]; then
   print_help
   echo -e "Input BAM files folder (-i) is required\n" >&2
   exit 1
fi

if [ -z "$REFERENCE" ]; then
   print_help
   echo -e "Reference genome FASTA file (-g) is required\n" >&2
   exit 1
fi

if [ -z "$OUTDIR" ]; then
   print_help
   echo -e "Path to the output folder (-o) is required\n" >&2
   exit 1
fi


# Sanity checks: 
# Check that: Input files exist; FASTA is indexed; there are input BAMs; all BAMs are indexed; CPUS >0;
# extra Platypus options do not contain options used within the pipeline
if [ ! -s $REFERENCE ]; then
    echo -e "\nERROR: Reference FASTA file not found or empty. Please check the path.\n" >&2
    exit 1
fi

if [ ! -s ${REFERENCE}.fai ]; then
    echo -e "\nERROR: Reference FASTA file has no accompanying .fai index file. Please index the FASTA file using 'samtools faidx' or equivalent.\n" >&2
    exit 1
fi

if  [ "$REGIONS" != "no" ] && [ ! -s $REGIONS ]; then
    echo -e "\nERROR: Regions file not found or empty. Please check the path.\n" >&2
    exit 1
fi

if ! [[ $CPUS =~ ^[1-9]+[0-9]*$ ]]; then
    echo -e "\nERROR: Number of CPUs must be greater than 0\n" >&2
    exit 1
fi

if echo "$EXTRA" | grep -q -E "\-\-logFileName|\-\-refFile|\-\-bamFiles|\-\-regions|\-\-minPosterior|\-\-minReads|\-\-minFlank|\-\-trimReadFlank|\-\-source|\-\-getVaria
ntsFromBAMs|\-\-nCPU|\-\-output=|\-o " ; then 
    echo -e "\nERROR: Additional Platypus options cannot include --logFileName, --refFile, --bamFiles, --regions, --minPosterior, --minReads, --minFlank, --trimReadFlan
k, --source, --getVariantsFromBAMs, --nCPU, --output, or -o.\n" >&2
    exit 1
fi

if [ ! -d $BAMSDIR ]; then
    echo -e "\nERROR: $BAMSDIR directory not found. Please check the path.\n" >&2
    exit 1
fi

FILES=`ls -1 $BAMSDIR/*.bam 2> /dev/null | wc -l`
if [ "$FILES" -eq 0 ]; then
    echo -e "\nERROR: $BAMSDIR contains no files with .bam extension. Please check the path.\n" >&2
    exit 1
fi

for FILE in `ls $BAMSDIR/*.bam`; do
    if [ ! -s ${FILE}.bai ]; then
        echo -e "\nERROR: The file $FILE has no accompanying .bai index file. Please index the file using 'samtools sort' and 'samtools index' or equivalent.\n" >&2
        exit 1
    fi
done



# START RUNNING
# Copy all standard out and standard error to log file
mkdir -p $OUTDIR/logs
exec &> >(tee -ia $OUTDIR/logs/SOMATYPUS_`date +"%y%m%d%H%M"`.log)

echo -e "\nThis is somatypus-farm-1 $VERSION\n"

echo "Input BAMs directory:   $BAMSDIR"
echo "Input reference genome: $REFERENCE"
echo "Input regions file:     $REGIONS"
echo "Output directory:       $OUTDIR"
echo "Number of CPUs to use:  $CPUS"
if [ -z "$EXTRA" ]; then
    echo "Extra Platypus options: no"
else
    echo "Extra Platypus options: $EXTRA"
fi


# # Check if there is a checkpoint file from a previous run in the output folder
# STEP=0
# if [ -s $OUTDIR/logs/CHECKPOINT ]; then
#     CHK=`tail -1 $OUTDIR/logs/CHECKPOINT`
#     STEP=`echo $CHK | cut -f1 -d" "`
#     STEPNAME=`echo $CHK | cut -f2 -d" "`
#     echo -e "\n*CHECKPOINT FILE FOUND*"
#     echo -e "Resuming execution after last completed step: $STEPNAME"
# fi


echo -e "\nExecution started on `date`"

# 6. MERGE THE VCFS ACCORDING TO CHR,POS,REF,ALT VALUES
echo -e "\n(6) MERGING FILTERED SNVS"
merge_calls
    
echo "6 merge calls" >> $OUTDIR/logs/CHECKPOINT

echo -e "\nsomatypus-farm-6 finished on `date`\n\n** Platypus jobs may still be running **\n"
